version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_DATABASE: ppai-ivr
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test123
      LANG: C.UTF-8
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: